version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      minor-patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
    commit-message:
      prefix: "[DEPS]"
