version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "prmack"  # Your GitHub username
    commit-message:
      prefix: "[DEPS]"
      include: "scope"
